version: '3.7'

services:
  car-sharing:
    build: ./car-sharing
    restart: always
    ports:
      - '5000:5000'
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env
    networks:
      - node-network
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/var/lib/mongo
    env_file:
      - .env
    healthcheck:
      test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]
      timeout: 20s
      retries: 10
    networks:
      - node-network
volumes:
  dbdata:
networks:
  node-network:
    driver: bridge